services:
  tests:
    build:
      context: .
      target: test
      platforms:
        - linux/amd64
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/blacklist_db
      BEARER_TOKEN: test-token

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blacklist_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d blacklist_db"]
      interval: 5s
      timeout: 5s
      retries: 10
